### ISSUE TITLE
Dag list 100 item limit defaulted

### ISSUE THREAD

**Issue by darrinpm** [necatiarslan/airflow-vscode-extension#12]
Populating the list of DAGs seems to only get the first 100. The UI's filter and is_active flag don't factor into the API call. 

Please increase the dag list limit to 999 or page your api call with offset param or pass the UI's filter or is_active flag in the API call.

**Comment by necatiarslan** [comment]
Yes, the dag list is the first 100 by default. I will Increase the limit to 999  in the next version (probably in a couple of days)
Pagination is also will be done.
I will add a dag hierarchy in the following versions for a better dag view.

Thanks for the feedback

**Comment by necatiarslan** [comment]
limit increased to 1000 with v1.4.2

**Comment by darrinpm** [comment]
Airflow bug with this :(. Tested the change (that was fast - thanks!!). Saw in the API call log that ?limit=1000 is now called, but Airflow returned 100 dags still. Browser test of API call was the same so guessing my version of Airflow has a bug. Offset works so will wait for that to be implemented! Suggest you drop limit to 100 when implementing offset.

**Comment by necatiarslan** [comment]
Thanks for the feedback. 
I will test it myself. If this is an Airflow API issue will escalate them.
