### ISSUE TITLE
Automaticly show all dags

### ISSUE THREAD

**Issue by Jekso** [necatiarslan/airflow-vscode-extension#13]
First of all very good effort on the extension really <3

I faced an annoying situation I run my airflow server and activate rest api but the dags do'esnt show immediatly I thought it's corrupted but then I remove show active dags filter and it works, my recommendation is to show all dags by default and thier status or you can split them into groups and show each one state

**Comment by necatiarslan** [comment]
The extension saves your show active dags choice and all other filters. 
When you click the big circle at the top and see all your dags (paused dags)(Filter should look like xFav, xActive, Filter:) it saves your current filters. 
When you re-open your vscode, it should show your all dags by default.
