### ISSUE TITLE
Bug in connections buttons

### ISSUE THREAD

**Issue by Jekso** [necatiarslan/airflow-vscode-extension#14]
I faced a bug in the connections list, it shows me my added connection and some extra connections called undefined and the username and password of my connection

another recommendation, you can put the default url automaticlly rather than I write it down in create connection input 

![image](https://user-images.githubusercontent.com/12834926/199152532-2a947684-ced4-410f-9d62-6e8d95fd7060.png)

**Comment by necatiarslan** [comment]
Do you know after which steps these buggy connections appeared?

**Comment by necatiarslan** [comment]
I released a new version v.1.4.3
In this version, you can clear servers with a new command.
Click ... next to the Refresh button and click Clear Servers.

I have fixed a possible buggy code also.
I hope this will help.
