### ISSUE TITLE
Question on Usage

### ISSUE THREAD

**Issue by ByrCWollam** [necatiarslan/airflow-vscode-extension#16]
I installed this extension thinking that the benefit would be that it would sync my DAGs that I'm developing to the Airflow server and then allow running them from within VSCode. After installing it seems that this is not the case as the Airflow view does not show the DAGs in my development environment, and I don't see any actions provided by the extension for copying my DAGs and plugins to the server. Have I misunderstood the usage of this extension? If so, how do you envision developers using this in authoring workflows?

**Comment by necatiarslan** [comment]
Hi, this extension does not deploy your DAGs to the Airflow server. It lists the DAGs that already exist on your Airflow server.
To deploy your DAGs (the python files) you should use a CICD tool or do it with your own method.

If you want to immediately test you develop in your local, you can use a airflow docker container to run airflow to run in your local and mount your local dags folder to this container. After that you can connect with this extension to your local airflow and trigger and monitor the DAGs.

I hope this helps.
