### ISSUE TITLE
issue: unclear where to enter local Airflow credentials

### ISSUE THREAD

**Issue by cptcret** [necatiarslan/airflow-vscode-extension#18]
I'm running a local copy of Airflow via Docker, have confirmed I can connect to the API on localhost.

I'm getting an error in VSCode saying "Please set Api URL, UserName and PassWord" when I try to refresh the list of servers on the extension.  It's not clear from the README or the extension where I should input this info.

**Comment by necatiarslan** [comment]
To connect your local airflow, you should click [+] at the top. First enter api url, user name and password
