### ISSUE TITLE
How to connect to remote Airflow Service?

### ISSUE THREAD

**Issue by em47390** [necatiarslan/airflow-vscode-extension#24]
Hi!

Thank you for sharing this great extension! Currenlty we're testing managing airflow DAGs in VS.
We already have an existing Airflow cluster, however, it seems whenever we test the connection based on the extension, the error below kept show up.

![image](https://github.com/necatiarslan/airflow-vscode-extension/assets/13690976/7a459fa4-6325-483e-a328-c52766624d8d)

I've tried add configuration in the user settings.json but failed too.

    _"airflow.api.url": "https://xxxxxx.xxxxxx.xx.com/airflow",
    "airflow.api.username": "admin",
    "airflow.api.password": "admin",_

Wondering is there specific configuration file we need update before use this extension to connect to the remote Airflow service?
Thank you for your support!

**Comment by necatiarslan** [comment]
Hi, Did you add your airflow server by clicking to plus [+] sign on the top menu.
it will ask you the server URL, user name and password.
you don't have to go to any config file.

URL should be like this one below
http://localhost:8080/api/v1

![image](https://github.com/necatiarslan/airflow-vscode-extension/assets/1336688/c3bd7dc7-9014-4f0c-a275-f1e50d3d275d)

**Comment by em47390** [comment]
Hi @necatiarslan ,

I tried upgrade to the latest VS code software today (previous version is 1.82),  and now the username & password textbox popup successfully after I click '+' button and input the URL !!
Thank you for your prompt reply and support!!

![image](https://github.com/necatiarslan/airflow-vscode-extension/assets/13690976/89eb5272-5292-4e3e-a1fd-425f67a5dbc6)
